version: '3.5'

services:

    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
            - DOCKER_VERNEMQ_LISTENER.tcp.allowed_protocol_versions=3,4,5
        image: erlio/docker-vernemq
        ports:
            - 1883:1883
        expose:
            - 1883

    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        depends_on:
            - vernemq
    
    server:
        build: ./
        volumes:
        - .:/app
        # environment:
        #     - PYTHONDONTWRITEBYTECODE=1
        #     - PYTHONUNBUFFERED=1
        ports:
            - 8000:8000
        depends_on:
            - db
    
    db:
        image: postgres:13-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    
    pgadmin4:
        image: dpage/pgadmin4
        ports:
        - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
